title: eashwar mohan
email: eashwar@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  A personal website for Eashwar Mohan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eashwar.github.io" # the base hostname & protocol for your site
twitter_username: _eashwar
github_username:  eashwar
excerpt_separator: <!--more-->

markdown: kramdown
kramdown:
    math_engine: mathjax
